spring:
  application:
    name: register
  cloud:
    config:
      uri: http://127.0.0.1:9000
      fail-fast: true
      password: admin
      username: user

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0 